// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonManagerService.Infrastructure.Contexts;

#nullable disable

namespace PersonManagerService.Infrastructure.Migrations
{
    [DbContext(typeof(PersonManagerServiceDbContext))]
    [Migration("20221208095128_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PersonManagerService.Domain.Models.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons", "dbo");

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("d1bc0e4d-b4a5-411f-b69a-47f877b2c4e7"),
                            FirstName = "Pera",
                            LastName = "Zdera"
                        },
                        new
                        {
                            PersonId = new Guid("0273b148-e1ba-4697-89ef-7df4a632c913"),
                            FirstName = "Mitar",
                            LastName = "Mitrovic"
                        });
                });

            modelBuilder.Entity("PersonManagerService.Domain.Models.PersonSkill", b =>
                {
                    b.Property<Guid>("PersonSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonSkillId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonSkills", "dbo");

                    b.HasData(
                        new
                        {
                            PersonSkillId = new Guid("4f09b36f-0b1f-40a6-8f33-39026d8e8b9c"),
                            Name = "debeo",
                            PersonId = new Guid("d1bc0e4d-b4a5-411f-b69a-47f877b2c4e7")
                        },
                        new
                        {
                            PersonSkillId = new Guid("9de7d1cc-3407-4d4b-9a10-9f65702564f6"),
                            Name = "spor",
                            PersonId = new Guid("d1bc0e4d-b4a5-411f-b69a-47f877b2c4e7")
                        },
                        new
                        {
                            PersonSkillId = new Guid("8d484b2d-2097-421c-a069-5b24c8992400"),
                            Name = "tanak",
                            PersonId = new Guid("0273b148-e1ba-4697-89ef-7df4a632c913")
                        },
                        new
                        {
                            PersonSkillId = new Guid("240d37fc-0bfd-4004-a775-e3060bbb312a"),
                            Name = "jak",
                            PersonId = new Guid("0273b148-e1ba-4697-89ef-7df4a632c913")
                        });
                });

            modelBuilder.Entity("PersonManagerService.Domain.Models.PersonSocialMediaAccount", b =>
                {
                    b.Property<Guid>("PersonSocialMediaAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SocialMediaAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonSocialMediaAccountId");

                    b.HasIndex("SocialMediaAccountId");

                    b.HasIndex("PersonId", "SocialMediaAccountId");

                    b.ToTable("PersonSocialMediaAccounts", "dbo");

                    b.HasData(
                        new
                        {
                            PersonSocialMediaAccountId = new Guid("cc0c20a1-c5b2-4d30-b950-95d9d04db362"),
                            Address = "pera@fb",
                            PersonId = new Guid("d1bc0e4d-b4a5-411f-b69a-47f877b2c4e7"),
                            SocialMediaAccountId = new Guid("c3fd6cd5-de6f-4280-9fe2-b650e63716fb")
                        },
                        new
                        {
                            PersonSocialMediaAccountId = new Guid("ad4d8bfb-c9ed-4102-b6aa-a658bc3b03d1"),
                            Address = "mita@fb",
                            PersonId = new Guid("0273b148-e1ba-4697-89ef-7df4a632c913"),
                            SocialMediaAccountId = new Guid("c3fd6cd5-de6f-4280-9fe2-b650e63716fb")
                        },
                        new
                        {
                            PersonSocialMediaAccountId = new Guid("34311ed3-31df-4e65-8785-a40d4c45581a"),
                            Address = "pera@tw",
                            PersonId = new Guid("d1bc0e4d-b4a5-411f-b69a-47f877b2c4e7"),
                            SocialMediaAccountId = new Guid("626fe0fc-7877-4a50-b5df-30c075eb251f")
                        },
                        new
                        {
                            PersonSocialMediaAccountId = new Guid("c0b0d53b-a44e-41dd-8d01-15cf00fde2d4"),
                            Address = "mita@tw",
                            PersonId = new Guid("0273b148-e1ba-4697-89ef-7df4a632c913"),
                            SocialMediaAccountId = new Guid("626fe0fc-7877-4a50-b5df-30c075eb251f")
                        });
                });

            modelBuilder.Entity("PersonManagerService.Domain.Models.SocialMediaAccount", b =>
                {
                    b.Property<Guid>("SocialMediaAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SocialMediaAccountId");

                    b.ToTable("SocialMediaAccounts", "dbo");

                    b.HasData(
                        new
                        {
                            SocialMediaAccountId = new Guid("c3fd6cd5-de6f-4280-9fe2-b650e63716fb"),
                            Type = "Facebook"
                        },
                        new
                        {
                            SocialMediaAccountId = new Guid("626fe0fc-7877-4a50-b5df-30c075eb251f"),
                            Type = "Twitter"
                        },
                        new
                        {
                            SocialMediaAccountId = new Guid("7af524e3-2d31-422e-845f-54e3de69c767"),
                            Type = "LinkedIn"
                        },
                        new
                        {
                            SocialMediaAccountId = new Guid("0795d1c7-4ffc-4be7-a8eb-362b78a9e232"),
                            Type = "Telegram"
                        });
                });

            modelBuilder.Entity("PersonManagerService.Domain.Models.PersonSkill", b =>
                {
                    b.HasOne("PersonManagerService.Domain.Models.Person", "Person")
                        .WithMany("PersonSkills")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PersonManagerService.Domain.Models.PersonSocialMediaAccount", b =>
                {
                    b.HasOne("PersonManagerService.Domain.Models.Person", "Person")
                        .WithMany("PersonSocialMediaAccounts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PersonManagerService.Domain.Models.SocialMediaAccount", "SocialMediaAccount")
                        .WithMany("PersonSocialMediaAccounts")
                        .HasForeignKey("SocialMediaAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Person");

                    b.Navigation("SocialMediaAccount");
                });

            modelBuilder.Entity("PersonManagerService.Domain.Models.Person", b =>
                {
                    b.Navigation("PersonSkills");

                    b.Navigation("PersonSocialMediaAccounts");
                });

            modelBuilder.Entity("PersonManagerService.Domain.Models.SocialMediaAccount", b =>
                {
                    b.Navigation("PersonSocialMediaAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
